font_family JetBrainsMono Nerd Font
font_size 12.0
disable_ligatures cursor

background_opacity 0.95
background_blur 20
window_padding_width 8
hide_window_decorations titlebar-only

scrollback_lines 10000

cursor_shape block
cursor_blink_interval 0

term xterm-kitty
allow_remote_control yes
listen_on unix:/tmp/mykitty
shell_integration enabled

copy_on_select yes
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
dynamic_title yes

mouse_hide_wait 2.0

enable_audio_bell no
visual_bell_duration 0.0

input_delay 3
repaint_delay 10
sync_to_monitor yes

detect_urls yes
url_style curly
open_url_with default

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_title_template " {index}: {title} "

include themes/current.conf

map kitty_mod+alt+l launch --type=background /Users/salo/.config/kitty/switch-theme light
map kitty_mod+alt+d launch --type=background /Users/salo/.config/kitty/switch-theme dark


# BEGIN_KITTY_THEME
# 1984 Dark
include current-theme.conf
# END_KITTY_THEME