--   use {
--     "microsoft/vscode-js-debug",
--     opt = true,
--     run = "npm install --legacy-peer-deps && npx gulp vsDebugServerBundle && mv dist out" 
--   }
-- 
--   use { 'nvim-treesitter/playground' }
--   use "nvim-treesitter/nvim-treesitter-textobjects"  -- enhance texetobject selection
--   use { 'michaelb/sniprun', run = 'sh ./install.sh'}

--   -- use "jsfaint/gen_tags.vim"
--   use "ray-x/cmp-treesitter"
--   use "f3fora/cmp-spell" -- spell check
--   use "tpope/vim-repeat" --  . command enhance
-- 
--   -- Language
--   use "vim-test/vim-test"
--   use {
--     "danymat/neogen",
--     config = function()
--         require('neogen').setup {
--           enabled = true,
--           languages = {
--               go = {
--                   template = {
--                       annotation_convention = "godoc",
--                   },
--               },
--           },
--         }
--     end,
--     tag = "2.20.0"
--   }
-- 
--   use "Shatur/neovim-tasks"
--   use "chrisbra/Colorizer"
