foreground #24292f
background #ffffff
selection_foreground #24292f
selection_background #bfdbfe

cursor #24292f
cursor_text_color #ffffff

url_color #0969da

active_tab_foreground #ffffff
active_tab_background #0969da
inactive_tab_foreground #57606a
inactive_tab_background #f6f8fa
tab_bar_background #eaeef2

active_border_color #0969da
inactive_border_color #d0d7de
bell_border_color #9a6700

color0 #24292f
color1 #cf222e
color2 #116329
color3 #4d2d00
color4 #0969da
color5 #8250df
color6 #1b7c83
color7 #6e7781
color8 #57606a
color9 #a40e26
color10 #1a7f37
color11 #633c01
color12 #218bff
color13 #a475f9
color14 #3192aa
color15 #8c959f
